import { GoogleGenerativeAI } from "@google/generative-ai";
import { getRobustModel, parseAIJson } from "@/lib/gemini";
import { NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { fetchGmailSnippets } from "@/lib/gmail";

export const dynamic = "force-dynamic";

export async function POST() {
  try {
    const session = await getServerSession(authOptions);
    //@ts-ignore
    const accessToken = session?.accessToken;
    const userEmail = session?.user?.email;

    if (!accessToken || !userEmail) {
      return NextResponse.json({ error: "Unauthorized. Please sign in again." }, { status: 401 });
    }

    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) throw new Error("GEMINI_API_KEY missing");

    const user = await prisma.user.upsert({
      where: { email: userEmail },
      update: {},
      create: { 
        email: userEmail,
        name: session.user?.name || userEmail.split('@')[0],
      }
    });

    const genAI = new GoogleGenerativeAI(apiKey);
    const model = await getRobustModel(genAI);

    // 1. Fetch latest unread emails
    const emails = await fetchGmailSnippets(accessToken);
    if (!emails || emails.length === 0) {
      return NextResponse.json({ status: "skipped", message: "No new unread emails." });
    }

    // 2. Filter out already processed emails using externalId in Task
    // Note: This is an optimization to avoid sending known emails to Gemini
    const existingIds = (await prisma.task.findMany({
      //@ts-ignore
      where: { externalId: { in: emails.map(e => e.id) } },
      //@ts-ignore
      select: { externalId: true }
    })).map(t => (t as any).externalId);

    const newEmails = emails.filter(e => !existingIds.includes(e.id));
    if (newEmails.length === 0) {
      return NextResponse.json({ status: "skipped", message: "All unread emails already processed." });
    }

    // 3. AI Distillation
    const emailPrompt = `
      You are an Task Extraction AI. Analyze these unread email snippets and identify ACTIONABLE items.
      
      EMAIL SNIPPETS:
      ${newEmails.map(e => `- ID: ${e.id} | From: ${e.from} | Subject: ${e.subject} | Snippet: ${e.snippet}`).join('\n')}

      GOAL:
      - Create a Task if an email implies a specific action required.
      - Create a Calendar Event if an email mentions a date/time (like a meeting, delivery, or flight).
      
      OUTPUT FORMAT (JSON ARRAY ONLY):
      [
        {"type": "task", "title": "...", "category": "Work/Personal", "externalId": "EMAIL_ID"},
        {"type": "event", "summary": "...", "startTime": "ISO", "endTime": "ISO", "externalId": "EMAIL_ID"}
      ]

      If NO actionable items are found, return exactly [].

      Categorize shopping/delivery/personal items as "Personal". Everything else as "Work".
      If an email is junk or not actionable, IGNORE it.

      IMPORTANT: Assume the current reference time is ${new Date().toLocaleString("en-US", {timeZone: "Asia/Kolkata"})}. 
      All relative times (tomorrow, next Friday) MUST be calculated based on this IST reference.
    `;

    const result = await model.generateContent(emailPrompt);
    const text = result.response.text();
    
    const actions = parseAIJson(text);
    const creations = { tasks: 0, events: 0 };

    for (const action of actions) {
      try {
        if (action.type === "task") {
          await prisma.task.create({
            data: {
              title: action.title,
              category: action.category || "Work",
              //@ts-ignore
              isAiGenerated: true,
              //@ts-ignore
              externalId: action.externalId,
              userId: user.id
            }
          });
          creations.tasks++;
        } 
        else if (action.type === "event") {
          // Push to Google Calendar
          const res = await fetch("https://www.googleapis.com/calendar/v3/calendars/primary/events", {
            method: "POST",
            headers: { "Authorization": `Bearer ${accessToken}`, "Content-Type": "application/json" },
            body: JSON.stringify({
              summary: `✨ ${action.summary}`, 
              description: `Generated by Dashboard AI from email: ${action.externalId}`,
              start: { 
                dateTime: action.startTime || new Date(Date.now() + 19800000).toISOString().replace('Z', ''), 
                timeZone: "Asia/Kolkata" 
              },
              end: { 
                dateTime: action.endTime || new Date(Date.now() + 23400000).toISOString().replace('Z', ''), 
                timeZone: "Asia/Kolkata" 
              }
            })
          });
          if (res.ok) creations.events++;
        }
      } catch (e) { console.error("Auto-creation error", e); }
    }

    return NextResponse.json({ 
      status: "success", 
      message: `Processed ${newEmails.length} emails.`,
      creations
    });

  } catch (error: any) {
    console.error("Gmail Sync Error:", error);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
